export { default as About } from './About'
export { default as Faq } from './Faq'
export { default as Privacy } from './Privacy'
export { default as TermOfUse } from './TermOfUse'
export { default as Search } from './Search'