module.exports = {
	REQUEST_TODOS: 'request todos',
	RECEIVE_TODOS: 'receive todos',

	REQUEST_CREATE_TODO: 'request create todo',
	RECEIVE_CREATE_TODO: 'receive create todo',

	REQUEST_TOGGLE_TODO: 'request update todo',
	RECEIVE_TOGGLE_TODO: 'receive update todo',

	ProjectEditorConstants: {
		Creator: {
			NAME_UPDATED: 'CREATOR_NAME_UPDATED',
			ICONSRC_UPDATED: 'CREATOR_ICONSRC_UPDATED',
			DESCRIPTION_UPDATED: 'CREATOR_DESCRIPTION_UPDATED',
		},
		Heading: {
			IMGSRC_UPDATED: 'HEADING_IMGSRC_UPDATED',
			LOGOSRC_UPDATED: 'HEADING_LOGOSRC_UPDATED',
			TITLE_UPDATED: 'HEADING_TITLE_UPDATED',
			DATEFROM_UPDATED: 'HEADING_DATEFROM_UPDATED',
			DATETO_UPDATED: 'HEADING_DATETO_UPDATED',
			CURRENTMONEY_UPDATED: 'HEADING_CURRENTMONEY_UPDATED',
			TARGETMONEY_UPDATED: 'HEADING_TARGETMONEY_UPDATED',
		},
		Overview: {
			Part1: {
				NEW_CONTENT: 'OVERVIEW_PART1_NEW_CONTENT',
				CONTENT_CHANGED: 'OVERVIEW_PART1_CONTENT_CHANGED',
				CONTENT_MOVED: 'OVERVIEW_PART1_CONTENT_MOVED',
				CONTENT_DELETED: 'OVERVIEW_PART1_CONTENT_DELETED',
			},
			Part2: {
				NEW_CONTENT: 'OVERVIEW_PART2_NEW_CONTENT',
				CONTENT_CHANGED: 'OVERVIEW_PART2_CONTENT_CHANGED',
				CONTENT_MOVED: 'OVERVIEW_PART2_CONTENT_MOVED',
				CONTENT_DELETED: 'OVERVIEW_PART2_CONTENT_DELETED',
			}
		},
		Rewards: {
			NEW_REWARD: 'REWARDS_NEW_REWARD',
			REWARD_CHANGED: 'REWARDS_REWARD_CHANGED',
			REWARD_MOVED: 'REWARDS_REWARD_MOVED',
			REWARD_DELETED: 'REWARDS_REWARD_DELETED',

		},
		Post: {
			Heading: {
				ICONSRC_UPDATED: 'POST_HEADING_ICONSRC_UPDATED',
				DESCRIPTION_UPDATED: 'POST_HEADING_DESCRIPTION_UPDATED',
			}
		}


	},

	Display: {
		MOBILE: 'display is mobilde',
		TABLET: 'display is tablet',
		DESKTOP: 'display is desktop',
	}
}
